environment:
  EXECUTABLE: "python.exe"
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\%EXECUTABLE% -m ensurepip"
  - "%PYTHON%\\%EXECUTABLE% -m pip install --upgrade pip setuptools"
  - "%PYTHON%\\%EXECUTABLE% -m pip install --upgrade codecov"

build: false

test_script:
  - "%PYTHON%\\%EXECUTABLE% setup.py test"
  - "%PYTHON%\\%EXECUTABLE% -m pip install -e ."
  - "%PYTHON%\\%EXECUTABLE% -m doctest README.md"

on_success:
  - "%PYTHON%\\%EXECUTABLE% -m codecov -f coverage.xml -X gcov"
