sudo: false
distro: trusty

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - python3 -m pip install codecov>=2.0.9

script:
  - python3 setup.py test

after_success:
  - codecov
