jobs:
- job: 'WindowsTest'
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016'
  strategy:
    matrix:
      Python35_x86:
        python.version: '3.5'
        python.architecture: 'x86'
      Python35_x64:
        python.version: '3.5'
        python.architecture: 'x64'
      Python36_x86:
        python.version: '3.6'
        python.architecture: 'x86'
      Python36_x64:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37_x86:
        python.version: '3.7'
        python.architecture: 'x86'
      Python37_x64:
        python.version: '3.7'
        python.architecture: 'x64'
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'
  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install packaging tools'
  - script: python setup.py test
    displayName: 'Run tests'
