version: '3'

services:
  lz:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: lycantropos/lz:0.0.0
    volumes:
      - ./lz/:/opt/lz/lz/
      - ./tests/:/opt/lz/tests/
      - ./README.md:/opt/lz/README.md
      - ./setup.py:/opt/lz/setup.py
      - ./setup.cfg:/opt/lz/setup.cfg
    entrypoint: python3
    command: setup.py test
