version: '3'

services:
  lz-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/lz-cpython:1.0.0-alpha
    volumes:
      - ./lz:/opt/lz/lz
      - ./pytest.ini:/opt/lz/pytest.ini
      - ./README.md:/opt/lz/README.md
      - ./requirements-tests.txt:/opt/lz/requirements-tests.txt
      - ./requirements.txt:/opt/lz/requirements.txt
      - ./setup.py:/opt/lz/setup.py
      - ./tests:/opt/lz/tests
    entrypoint: pytest
