version: '3'

services:
  lz-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/lz-cpython:0.6.1-alpha
    volumes:
      - ./lz/:/opt/lz/lz/
      - ./tests/:/opt/lz/tests/
      - ./README.md:/opt/lz/README.md
      - ./setup.py:/opt/lz/setup.py
      - ./setup.cfg:/opt/lz/setup.cfg
    entrypoint: python
    command: setup.py test
