version: '3'

services:
  lz-pypy:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${PYPY_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/lz-pypy:0.10.0-alpha
    volumes:
      - ./lz/:/opt/lz/lz/
      - ./tests/:/opt/lz/tests/
      - ./README.md:/opt/lz/README.md
      - ./requirements.txt:/opt/lz/requirements.txt
      - ./requirements-tests.txt:/opt/lz/requirements-tests.txt
      - ./setup.py:/opt/lz/setup.py
      - ./setup.cfg:/opt/lz/setup.cfg
    entrypoint: pytest
